#!/usr/bin/env bash

# ***This script was made by Clay Gomera (Drake)***
#  - Description: A simple desktop dmenu script
#  - Dependencies: dmenu, j4-dmenu-desktop

prompt="-p launch:"
colors="-nb \#1d2021 -nf \#fbf1c7 -sb \#cc241d -sf \#fbf1c7"
font="-fn 'mononoki Nerd Font-10'"

DMENU="dmenu -i -l 10 $font $colors $prompt"
j4-dmenu-desktop --dmenu "$DMENU" --no-generic
