#!/usr/bin/env bash

# ***This script was made by Clay Gomera (Drake)***
#  - Description: A simple desktop dmenu script
#  - Dependencies: dmenu, j4-dmenu-desktop
#
j4-dmenu-desktop --dmenu "dmenu -i -l 10 -p launch:" --no-generic
