#!/usr/bin/env bash

# dmenu_wall - A dmenu script to set the wallpaper on X using xwallpaper
# Author: Lian Dynn (Dynnian)
# Dependencies: dmenu, fd, xwallpaper

# Directory containing wallpapers
walldir="$XDG_PICTURES_DIR/Wallpapers"
restorescript="$XDG_SOURCE_HOME/dwm/scripts/restorewall"

# Change to wallpaper directory or exit if it fails
cd "$walldir" || exit

# Define wallpaper options for xwallpaper
option1="Fill"
option2="Center"
option3="Tile"
option4="Maximize"
option5="Stretch"
options="$option1\n$option2\n$option3\n$option4\n$option5"

# Prompt user to select a wallpaper
wallpaper=$(fd -p ./ | dmenu -i -p "󰋩 Select a wallpaper")
if [ -z "$wallpaper" ]; then
    exit 0
fi

# Store the selected wallpaper
chosenwall="$wallpaper"

# Function to generate a script to restore wallpaper
generateScript() {
    echo "#!/bin/sh" > "$restorescript"
    echo "xwallpaper $1 \"$walldir/$chosenwall\"" >> "$restorescript"
    chmod +x "$restorescript"
}

# Prompt user to select a wallpaper format
action=$(echo -e "$options" | dmenu -i -p " Choose the format")
case "$action" in
    "$option1")
        xwallpaper --zoom "$chosenwall"
        generateScript "--zoom"
        ;;
    "$option2")
        xwallpaper --center "$chosenwall"
        generateScript "--center"
        ;;
    "$option3")
        xwallpaper --tile "$chosenwall"
        generateScript "--tile"
        ;;
    "$option4")
        xwallpaper --maximize "$chosenwall"
        generateScript "--maximize"
        ;;
    "$option5")
        xwallpaper --stretch "$chosenwall"
        generateScript "--stretch"
        ;;
esac
