#!/usr/bin/env bash

# dmenu_drun - Just a script to wrap j4-dmenu-desktop
# Author: Lian Dynn (Drake)
# Dependencies: dmenu, j4-dmenu-desktop

# uses j4-dmenu-desktop to launch programs by it's desktop entry
j4-dmenu-desktop --dmenu "dmenu -i -l 10 -p '󱓞 Launch:'" --no-generic
