#!/usr/bin/env bash

# Toggle between 'us' and 'es' keyboard layouts
current_layout=$(setxkbmap -query | awk '/layout:/ {print $2}')

if [[ "$current_layout" == "us" ]]; then
    setxkbmap es
else
    setxkbmap us
fi
