#!/bin/sh

cd "$HOME" || exit 1

# Session settings
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_DESKTOP=sway
export XDG_SESSION_TYPE=wayland
export EGL_PLATFORM=wayland
export SDL_VIDEODRIVER=wayland
export CLUTTER_PLATFORM=wayland
export QT_QPA_PLATFORM=wayland
export QT_STYLE_OVERRIDE=kvantum
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export XKB_DEFAULT_LAYOUT=us
export MOZ_ENABLE_WAYLAND=1
export MOZ_WAYLAND_USE_VAAPI=1
export MOZ_DISABLE_RDD_SANDBOX=1 

# GTK & cursor stuff
export XCURSOR_PATH="$XDG_DATA_HOME/icons/"
export XCURSOR_THEME="Simp1e-Gruvbox-Dark"
export GTK_THEME="gruvbox-dark-gtk"
export GTK_ICON_THEME="gruvbox-dark-icons-gtk"
export GTK_CURSOR_THEME="Simp1e-Gruvbox-Dark"

# User defined enviroment variables
export RUNNER="fuzzel --dmenu"
export WM=sway

# Start compositor
dbus-launch $WM
