# -*- conf -*-

# For documentation on these options, see `man fnott.ini`

# =======================
# General Options
# =======================

# output=<undefined>#
# min-width=0
# max-width=0
# max-height=0
stacking-order=bottom-up
anchor=top-right
icon-theme=Papirus-Dark
selection-helper=fuzzel --dmenu0
selection-helper-uses-null-separator=true
play-sound=paplay ${filename}
sound-file=/usr/share/sounds/ocean/stereo/message-contact-in.oga
layer=top
dpi-aware=yes

# Timeout values are in seconds. 0 to disable
max-timeout=10
default-timeout=5
# idle-timeout=0

# =======================
# Fonts and Formating
# =======================

# title
title-font=Mononoki Nerd Font:size=6
title-format= # don't want this printed

# summary
summary-font=Mononoki Nerd Font:size=8
summary-format=<i>%s</i>\n

# body
body-font=Mononoki Nerd Font:size=8
body-format=%b

# =======================
# Appearance
# =======================

# sizes, paddings, margins
max-icon-size=32
edge-margin-vertical=5
edge-margin-horizontal=5
notification-margin=8
border-radius=0
border-size=3
padding-vertical=18
padding-horizontal=18
progress-bar-height=20
#icon= # dont want an icon

# colors
background=1d2021ff
border-color=cc241dff
title-color=fbf1c7ff
summary-color=ebdbb2ff
body-color=ebdbb2ff
progress-bar-color=fbf1c7ff


# =======================
# Priorities (low, normal, critical)
# =======================

# [low]
# background=2b2b2bff
# title-color=888888ff
# summary-color=888888ff
# body-color=888888ff

# [normal]

[critical]
background=1d2021ff
border-color=fb4934ff
