preload = $HOME/.config/hypr/wall/wall.png
wallpaper = eDP-1,$HOME/.config/hypr/wall/wall.png
wallpaper = HDMI-A-2,$HOME/.config/hypr/wall/wall.png
wallpaper = DP-1,$HOME/.config/hypr/wall/wall.png
wallpaper = DP-3,$HOME/.config/hypr/wall/wall.png
splash = false
