#!/usr/bin/env bash

# rs_wall - A simple screenshot menu script for rofi/dmenu/wofi/fuzzel
# Author: Clay Gomera (Drake)
# Dependencies: fuzzel, wob

############################
# Configuration Parameters #
############################
walldir="$XDG_PICTURES_DIR/Wallpapers" # wallpapers folder, change it to yours

####################
# Main Script Flow #
####################

cd "$walldir" || exit 1
wallpaper=$(/bin/ls | sort -n | $RUNNER -l 5 -i -p "[󰋩 Wallpaper Selector]  ")
if [ -n "$wallpaper" ]; then
    if [[ "$wallpaper" == *.jpg ]]; then
        rm -f "$HOME/.config/sway/wallpaper/"*
        cp "$wallpaper" "$HOME/.config/sway/wallpaper/background.jpg"
        cp "$wallpaper" "$HOME/.config/sway/wallpaper/locked.jpg"
        swaymsg output \* bg "$HOME/.config/sway/wallpaper/background.jpg" fill
    elif [[ "$wallpaper" == *.png ]]; then
        rm -f "$HOME/.config/sway/wallpaper/"*
        cp "$wallpaper" "$HOME/.config/sway/wallpaper/background.png"
        cp "$wallpaper" "$HOME/.config/sway/wallpaper/locked.png"
        swaymsg output \* bg "$HOME/.config/sway/wallpaper/background.png" fill
    fi
else
    exit 1
fi
exit 0
