#!/usr/bin/env bash

# rs_wall - A simple screenshot menu script for rofi/dmenu/wofi/fuzzel
# Author: Lian Drake
# Dependencies: fuzzel, hyprpaper

walldir="$XDG_PICTURES_DIR/Wallpapers" # wallpapers folder, change it to yours

cd "$walldir" || exit 1
wallpaper=$(/bin/ls | sort -n | $RUNNER --match-mode fzf -l 5 -i -p "[󰋩 Wallpaper Selector]  ")
if [ -n "$wallpaper" ]; then
    cp "$wallpaper" "$HOME/.config/hypr/wall/wall.png"
    cp "$wallpaper" "$HOME/.config/hypr/wall/lock.png"
    pidof hyprpaper && pkill hyprpaper
    sleep 0.5
    hyprpaper &
    disown
else
    exit 0
fi
exit 0
