#!/bin/bash
currntpwr=$(powerprofilesctl get)
if [ "${currntpwr}" = "performance" ]; then
  pwr="󰓅"
elif [ "${currntpwr}" = "balanced" ]; then
  pwr="󰾅"
elif [ "${currntpwr}" = "power-saver" ]; then
  pwr="󰾆"
fi
echo "$pwr"
