#!/bin/bash
brt=$(xbacklight -get)
if [ "${brt%.*}" -eq 100 ]; then
    icon="󰛨"
elif [ "${brt%.*}" -ge 90 ]; then
    icon="󱩖"
elif [ "${brt%.*}" -ge 80 ]; then
    icon="󱩕"
elif [ "${brt%.*}" -ge 70 ]; then
    icon="󱩔"
elif [ "${brt%.*}" -ge 60 ]; then
    icon="󱩓"
elif [ "${brt%.*}" -ge 50 ]; then
    icon="󱩒"
elif [ "${brt%.*}" -ge 40 ]; then
    icon="󱩑"
elif [ "${brt%.*}" -ge 30 ]; then
    icon="󱩐"
elif [ "${brt%.*}" -ge 20 ]; then
    icon="󱩏"
else
    icon="󱩎"
fi
echo " $icon ${brt%.*}% "
