#!/bin/sh
##       ____             __                               ##
##      / __ \_________ _/ /_____                          ##
##     / / / / ___/ __ `/ //_/ _ \                         ##
##    / /_/ / /  / /_/ / ,< /  __/  Clay Gomera (Drake)    ##
##   /_____/_/   \__,_/_/|_|\___/   My custom dwm build    ##

/usr/libexec/kf5/polkit-kde-authentication-agent-1 &
dwmblocks &
sh "$HOME"/.fehbg &
unclutter --hide-on-touch &
herbed &
picom --config "$HOME/.config/picom/picom.conf" &

/usr/bin/gnome-keyring-daemon --start &
export SSH_AUTH_SOCK
export GPG_AGENT_INFO
export GNOME_KEYRING_CONTROL
export GNOME_KEYRING_PID
