#!/usr/bin/env bash
##       ____             __                               ##
##      / __ \_________ _/ /_____                          ##
##     / / / / ___/ __ `/ //_/ _ \                         ##
##    / /_/ / /  / /_/ / ,< /  __/  Clay Gomera (Drake)    ##
##   /_____/_/   \__,_/_/|_|\___/   My custom dwm build    ##

# activate neccesary env variables for X11
dbus-update-activation-environment DISPLAY XAUTHORITY &

# configure input
$XDG_SOURCE_HOME/dwm/scripts/input &

# set monitor settings and restore wallpaper
$XDG_SOURCE_HOME/dwm/scripts/monitors && sh "$XDG_SOURCE_HOME/dwm/scripts/restorewall" &

# set theming and font thingy
$XDG_SOURCE_HOME/dwm/scripts/theme &

# autostart programs, use pidof <program> || program, to prevent relaunching stuff if dwm is restarted 
pidof dwmblocks || dwmblocks &
pidof picom || picom &
pidof xidlehook || $XDG_SOURCE_HOME/dwm/scripts/idle &
pidof xss-lock || xss-lock -- "$XDG_SOURCE_HOME/dwm/scripts/lock" &
pidof unclutter || unclutter --hide-on-touch &
pidof dunst || dunst --config $XDG_CONFIG_HOME/dunst/dunstrc &
pidof polkit-gnome-authentication-agent-1 || /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
pidof clipmenud || clipmenud &
pidof emacs || /usr/bin/emacs --daemon &
pidof nextcloud || flatpak run com.nextcloud.desktopclient.nextcloud --background &
