#!/bin/bash

# Commands to dim and restore brightness across all monitors
DIM_CMD="for output in \$(xrandr --listmonitors | awk '/^\s*[0-9]+:/ {print \$4}'); do xrandr --output \"\$output\" --brightness 0.5; done"
NORMAL_CMD="for output in \$(xrandr --listmonitors | awk '/^\s*[0-9]+:/ {print \$4}'); do xrandr --output \"\$output\" --brightness 1.0; done"

# Start xidlehook
pidof xidlehook || xidlehook \
    --detect-sleep \
    --not-when-fullscreen \
    --not-when-audio \
    --timer 60 \
        "$DIM_CMD" \
        "$NORMAL_CMD" \
    --timer 30 \
        "$XDG_SOURCE_HOME/dwm/scripts/lock" \
        "$NORMAL_CMD"
