#!/usr/bin/env bash

# Wait for X to be ready
while ! xinput list >/dev/null 2>&1; do
    sleep 0.5
done

# Detect device
if xinput list | grep -q "VEN_0488:00 0488:104B Touchpad"; then
    # Dell Precision 3581
    TOUCHPAD="VEN_0488:00 0488:104B Touchpad"
elif xinput list | grep -q "Virtual core pointer"; then
    # ThinkPad T480
    TOUCHPAD="Virtual core pointer"
else
    echo "Touchpad not found."
    exit 1
fi

echo "Configuring touchpad: $TOUCHPAD"

# Wait until the device is ready
while ! xinput list | grep -q "$TOUCHPAD"; do
    sleep 0.5
done

# Touchpad settings
xinput set-prop "$TOUCHPAD" "libinput Tapping Enabled" 1
xinput set-prop "$TOUCHPAD" "libinput Click Method Enabled" 1 0
xinput set-prop "$TOUCHPAD" "libinput Natural Scrolling Enabled" 1
xinput set-prop "$TOUCHPAD" "libinput Disable While Typing Enabled" 0

